#!/usr/bin/env node
/**
 * Bump the iOS build number in the two places that have to agree.
 *
 * Xcode reads ONLY ios/Dawrah/Info.plist when it archives. app.json is what
 * survives in git, because /ios is gitignored and regenerated by prebuild. Edit
 * one without the other and you either archive a stale number (plist untouched)
 * or lose the bump the next time prebuild runs (app.json untouched). Build 4
 * shipped twice because of the first of those.
 *
 *   npm run bump-build        bump by one
 *   npm run bump-build -- 12  set it to 12
 */
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const root = path.join(__dirname, '..');
const appJsonPath = path.join(root, 'app.json');
const plistPath = path.join(root, 'ios', 'Dawrah', 'Info.plist');

// Patched as text rather than parsed and re-serialised: app.json is hand
// maintained and JSON.stringify would reformat every unrelated line of it.
const src = fs.readFileSync(appJsonPath, 'utf8');
const match = src.match(/("buildNumber"\s*:\s*")(\d+)(")/);
if (!match) {
  console.error('app.json has no numeric expo.ios.buildNumber to bump.');
  process.exit(1);
}

const current = parseInt(match[2], 10);
const explicit = process.argv[2];
const next = explicit === undefined ? current + 1 : parseInt(explicit, 10);

if (!Number.isInteger(next) || next < 1) {
  console.error(`Not a build number: ${explicit}`);
  process.exit(1);
}
if (next <= current) {
  // App Store Connect refuses a CFBundleVersion it has already seen under the
  // same version string, so going backwards is never what anyone meant.
  console.error(`Refusing to go from ${current} to ${next}. Build numbers only rise.`);
  process.exit(1);
}

fs.writeFileSync(
  appJsonPath,
  src.replace(match[0], `${match[1]}${next}${match[3]}`)
);
console.log(`app.json         buildNumber      ${current} -> ${next}`);

if (!fs.existsSync(plistPath)) {
  // Nothing to sync yet. prebuild will write the number out of app.json.
  console.log('Info.plist       (absent, prebuild will write it)');
} else {
  execFileSync('/usr/libexec/PlistBuddy', ['-c', `Set :CFBundleVersion ${next}`, plistPath]);
  const check = execFileSync('/usr/libexec/PlistBuddy', ['-c', 'Print :CFBundleVersion', plistPath])
    .toString()
    .trim();
  if (check !== String(next)) {
    console.error(`Info.plist still reads ${check}. Xcode would archive that, not ${next}.`);
    process.exit(1);
  }
  console.log(`Info.plist       CFBundleVersion  -> ${check}`);
}

console.log('\nNext: npx expo export   (runs hermesc, which the archive also runs)');
console.log('Then: Xcode Product > Archive');
